version: '3.4'
services:
  db:
    restart: always
    image: postgres:11
    env_file: env/pg.env
    volumes:
      - ./db:/var/lib/postgresql/data:z

  app:
    build: .
    restart: always
    user: '101'
    env_file: env/dcassistant.env
    depends_on:
      - db
    volumes:
      - ./static:/app/dc_assistant/dc_assistant/static:ro
      - ./media:/app/dc_assistant/dc_assistant/media:z
      
  nginx:
    command: nginx -c /etc/nginx/nginx_dcassistant.conf
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8080
    volumes:
      - ./static:/app/dc_assistant/dc_assistant/static:ro

